In [2]:
import numpy as np

a=np.array([[1,2],[3,4]])
b=np.array([-1, -2])
print(a+b)
# 크기가 다른 배열 간 연산이 가능한 이유는 브로드캐스팅 때문임. 
# 브로드캐스팅이란 다른 크기의 배열에 유니버설 함수를 적용하는 규칙의 집합.
# 브로드캐스팅 대상이 되는 배열은 특정 차원의 크기가 반드시 1이어야만 한다.

[[0 0]
 [2 2]]


In [3]:
x=[[1,2], [3,4]]
print(x[0][1]) # 리스트 안에 리스트가 있는 구조. 두 번 인덱싱해서 접근한다.

x=np.array(x)
print(x[0,1]) # 넘파이 배열은 행렬이라고 했다. 즉 0행 2열을 인덱싱.

2
2


In [4]:
x=np.arange(1,10)
print(x[[0,3]]) # [0,3]이 x의 인덱스로 사용되어, 0번째와 3번째 요소인 1과 4가 반환되었다.

y=np.array([[1,2],[3,4],[5,6]])
print(y[0,1]) # 0행 1열에 있는 값 출력
print(y[[0,1]]) # 0번째 요소, 1번째 요소 출력

[1 4]
2
[[1 2]
 [3 4]]


In [5]:
x=np.arange(20)
print(x)
x=np.arange(20).reshape(4,5)
print(x)
print(x[1, [1,-1]]) # 1번째 행의 1번째 열과 -1번째 열 인덱싱
print(x[0, 0:3]) # 0번째 행의 0번째 열부터 3번째 열까지 슬라이싱
print(x[[0,1],[2,3]]) # (0,2), (1,3) 셀 인덱싱. 팬시 인덱싱은 (행, 열) 쌍을 개별적으로 지정한다.

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[6 9]
[0 1 2]
[2 8]


In [6]:
x=np.array([1,2,3,4,5])
b=[True, False, True, True, False]
print(x[b])

[1 3 4]


In [8]:
x=np.array([1,2,3,4,5])
cond= x >= 3  # x의 요소가 3보다 크거나 같은지를 나타내는 부울 배열을 cond에 저장한다.
print(cond)
print(x[cond]) # x를 cond로 필터링한 결과를 출력한다. cond의 True와 같은 위치에 있는 3,4,5가 출력됨.

[False False  True  True  True]
[3 4 5]
