**ndarray는 수학의 벡터, 행렬을 위해 만들어진 자료형이다.**

In [3]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3.0])
arr3 = np.array([1,2,"3"])

print(arr1, arr1.dtype)
print(arr2, arr2.dtype)
print(arr3, arr3.dtype) # 모든 요소의 자료형이 하나로 통일됨

[1 2 3] int32
[1. 2. 3.] float64
['1' '2' '3'] <U11


In [7]:
arr1 = np.array([1,2,3]) # 1차원
arr2 = np.array([[1,2,3], [4,5,6]]) # 2차원
arr3 = np.array([[[1,2],[3,4]],[[5,6], [7,8]]]) # 3차원

print(arr1.shape) # 크기가 3인 벡터
print(arr2.shape) # 크기가 2*3인 행렬
print(arr3.shape) # 크기가 2*2*2인 텐서

(3,)
(2, 3)
(2, 2, 2)


In [12]:
# arrange()와 linspace()는 연속하는 요소로 구성된 ndarray를 생성한다.
arr1 = np.arange(5) # 0부터 5까지 1씩 증가
arr2 = np.arange(-1, 4.5, 1.5) # -1부터 4.5까지 1.5씩 증가
arr3 = np.arange(10, 1, -1) # 10부터 1까지 -1씩 증가
arr4 = np.linspace(0, 1, 11) # 0부터 1까지 등간격의 11개 요소 생성, 시작점과 끝점 포함.

print("np.arange(5):{}".format(arr1))
print("np.arange(-1, 4.5, 1.5):{}".format(arr2))
print("np.arange(10, 1, -1):{}".format(arr3))
print("np.linspace(0,1,11):{}".format(arr4))

np.arange(5):[0 1 2 3 4]
np.arange(-1, 4.5, 1.5):[-1.   0.5  2.   3.5]
np.arange(10, 1, -1):[10  9  8  7  6  5  4  3  2]
np.linspace(0,1,11):[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [14]:
arr1 = np.zeros(5) #크기: 5
arr2 = np.zeros((3,2)) # 크기: (3,2)
arr3 = np.zeros((2,2), dtype = bool) # 크기: (2,2), 자료형: bool

print(arr1)
print(arr2)
print(arr3)

[0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[False False]
 [False False]]


In [20]:
arr1 = np.random.random(5) # 크기가 5인 1차원 난수 배열 생성
arr2 = np.random.random((2,2)) # 크기가 (2,2)인 2차원 난수 배열 생성. 2차원 배열 = 행렬(Matrix)
print(arr1)
print(arr2)

[0.17343191 0.78997187 0.39721306 0.35523616 0.84870124]
[[0.83953462 0.03384725]
 [0.49423896 0.76094123]]


In [21]:
arr3= np.random.normal(0,1,5)  
arr4= np.random.normal(10,3, (3,3)) # 평균 10, 표준편차 3인 정규분포를 따르는 크기 (3,3)의 2차원 배열 생성
print(arr3)
print(arr4)

[ 0.21102285 -0.65355678 -0.39671271 -2.10085265  1.0779741 ]
[[13.29893421 12.69001147  5.3198601 ]
 [ 9.85945469  4.15943159 12.22852784]
 [10.44241022 15.09326222  8.17216184]]


In [27]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr1.reshape(3,2))  # (6,) → (3,2)
print(arr2.reshape(-1,2)) # -1을 쓴건 알아서 계산하라는 것임. 즉, (2,3) → (?,2)
print(arr1.reshape(-1,1)) # 행벡터를 열벡터로 바꿀 때, (-1,1). 즉, (6,) → (?,1)

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
