In [2]:
import numpy as np

x=np.arange(15).reshape(5,3)
display(x)  # 표나 그림 등 원래 모양을 유지한 채로 출력해야 할 때 display를 사용.
print(np.sum(x)) # 넘파이 라이브러리가 제공하는 독립적인 함수이다. ndarray가 아닌 배열 자료형(튜플, 리스트 등)에도 사용 가능.
print(x.sum()) # 우리가 만든 넘파일 배열 x 자체가 갖는 메서드다. 그러므로 리스트에는 사용 불가능.

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

105
105


In [3]:
x=np.arange(15).reshape(5,3)
# 행을 따라 위에서 아래로 계산한다. axis = 0
print(np.sum(x, axis = 0))
print(x.sum(axis = 0))

# 열을 따라 왼쪽에서 오른쪽으로 계산한다. axis = 1
print(np.sum(x, axis = 1))
print(x.sum(axis = 1))

[30 35 40]
[30 35 40]
[ 3 12 21 30 39]
[ 3 12 21 30 39]


In [5]:
x=np.arange(15).reshape(5,3)
print("열별 합계: {}".format(np.sum(x, axis=0)))
print("전체 합계: {}".format(np.sum(x)))
print("행별 최솟값: {}".format(x.min(axis = 1)))
print("열 방향 최솟값: {}".format(x.min(axis = 0)))
print("전체 최솟값: {}".format(x.min()))
print("전체 최댓값: {}".format(x.max()))
print("열별 표준편차: {}".format(np.std(x, axis=0)))
print("전체 중위수: {}".format(np.median(x)))
print("전체 상위 20%: {}".format(np.quantile(x, 0.2)))
print("유니크한 값 목록: {}".format(np.unique(x)))

열별 합계: [30 35 40]
전체 합계: 105
행별 최솟값: [ 0  3  6  9 12]
열 방향 최솟값: [0 1 2]
전체 최솟값: 0
전체 최댓값: 14
열별 표준편차: [4.24264069 4.24264069 4.24264069]
전체 중위수: 7.0
전체 상위 20%: 2.8000000000000003
유니크한 값 목록: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
